// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PancheriaJP.Config;

#nullable disable

namespace PancheriaJP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PancheriaJP.Models.Pancho.Pancho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Aderezos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVegano")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Panchos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aderezos = "[\"Mayonesa\",\"Mostaza\"]",
                            IsVegano = false,
                            Nombre = "Normal",
                            Precio = 12.5
                        },
                        new
                        {
                            Id = 2,
                            Aderezos = "[\"Mayonesa\",\"Mostaza\",\"Papitas\"]",
                            IsVegano = false,
                            Nombre = "Super Pancho",
                            Precio = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
