create procedure GetErrorInfo
as
Begin
	SELECT ERROR_NUMBER() AS ErrorNumber,
	ERROR_SEVERITY() AS ErrorSeverity,
	ERROR_STATE() AS ErrorState,
	ERROR_PROCEDURE() AS ErrorProcedure,
	ERROR_LINE() AS ErrorLine,
	ERROR_MESSAGE() AS ErrorMessage;
End;

CREATE PROCEDURE I_Institucion
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(256)
   ,@DOMICILIO VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Institucion
    (NOMBRE ,DOMICILIO)
    VALUES
    (@NOMBRE ,@DOMICILIO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Institucion
    @ID INT
   ,@NOMBRE VARCHAR(256)
   ,@DOMICILIO VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    UPDATE Institucion SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DOMICILIO = ISNULL(@DOMICILIO, DOMICILIO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Institucion
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Institucion WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_TipoCarrera
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO TipoCarrera
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_TipoCarrera
    @ID INT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    UPDATE TipoCarrera SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_TipoCarrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM TipoCarrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_ModalidadCarrera
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO ModalidadCarrera
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_ModalidadCarrera
    @ID INT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    UPDATE ModalidadCarrera SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_ModalidadCarrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM ModalidadCarrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Carrera
    @ID INT OUTPUT
   ,@INSTITUCION_ID INT
   ,@TIPOCARRERA_ID INT
   ,@MODALIDADCARRERA_ID INT
   ,@NOMBRE VARCHAR(256)
   ,@DURACION INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Carrera
    (INSTITUCION_ID ,TIPOCARRERA_ID ,MODALIDADCARRERA_ID ,NOMBRE ,DURACION)
    VALUES
    (@INSTITUCION_ID ,@TIPOCARRERA_ID ,@MODALIDADCARRERA_ID ,@NOMBRE ,@DURACION)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Carrera
    @ID INT
   ,@INSTITUCION_ID INT
   ,@TIPOCARRERA_ID INT
   ,@MODALIDADCARRERA_ID INT
   ,@NOMBRE VARCHAR(256)
   ,@DURACION INT
AS
BEGIN
  BEGIN TRY
    UPDATE Carrera SET
    INSTITUCION_ID = ISNULL(@INSTITUCION_ID, INSTITUCION_ID)
   ,TIPOCARRERA_ID = ISNULL(@TIPOCARRERA_ID, TIPOCARRERA_ID)
   ,MODALIDADCARRERA_ID = ISNULL(@MODALIDADCARRERA_ID, MODALIDADCARRERA_ID)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DURACION = ISNULL(@DURACION, DURACION)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Carrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Carrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Regimen
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Regimen
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Regimen
    @ID INT
   ,@NOMBRE VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    UPDATE Regimen SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Regimen
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Regimen WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Area
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Area
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Area
    @ID INT
   ,@NOMBRE VARCHAR(256)
AS
BEGIN
  BEGIN TRY
    UPDATE Area SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Area
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Area WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_PlanEstudio
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(256)
   ,@CARRERA_ID INT
   ,@FECHA_INICIO DATETIME
   ,@FECHA_FIN DATETIME
AS
BEGIN
  BEGIN TRY
    INSERT INTO PlanEstudio
    (NOMBRE ,CARRERA_ID ,FECHA_INICIO ,FECHA_FIN)
    VALUES
    (@NOMBRE ,@CARRERA_ID ,@FECHA_INICIO ,@FECHA_FIN)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_PlanEstudio
    @ID INT
   ,@NOMBRE VARCHAR(256)
   ,@CARRERA_ID INT
   ,@FECHA_INICIO DATETIME
   ,@FECHA_FIN DATETIME
AS
BEGIN
  BEGIN TRY
    UPDATE PlanEstudio SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,CARRERA_ID = ISNULL(@CARRERA_ID, CARRERA_ID)
   ,FECHA_INICIO = ISNULL(@FECHA_INICIO, FECHA_INICIO)
   ,FECHA_FIN = ISNULL(@FECHA_FIN, FECHA_FIN)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_PlanEstudio
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM PlanEstudio WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Cuatrimestre
    @ID INT OUTPUT
   ,@NUMERO INT
   ,@DESCRIPCION VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Cuatrimestre
    (NUMERO ,DESCRIPCION)
    VALUES
    (@NUMERO ,@DESCRIPCION)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Cuatrimestre
    @ID INT
   ,@NUMERO INT
   ,@DESCRIPCION VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    UPDATE Cuatrimestre SET
    NUMERO = ISNULL(@NUMERO, NUMERO)
   ,DESCRIPCION = ISNULL(@DESCRIPCION, DESCRIPCION)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Cuatrimestre
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Cuatrimestre WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Nivel
    @ID INT OUTPUT
   ,@NUMERO INT
   ,@DESCRIPCION VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Nivel
    (NUMERO ,DESCRIPCION)
    VALUES
    (@NUMERO ,@DESCRIPCION)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Nivel
    @ID INT
   ,@NUMERO INT
   ,@DESCRIPCION VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    UPDATE Nivel SET
    NUMERO = ISNULL(@NUMERO, NUMERO)
   ,DESCRIPCION = ISNULL(@DESCRIPCION, DESCRIPCION)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Nivel
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Nivel WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Asignatura
    @ID INT OUTPUT
   ,@AREA_ID INT
   ,@REGIMEN_ID INT
   ,@NOMBRE VARCHAR(256)
   ,@HORASSEMANA INT
   ,@HORASCUATRIMESTRE INT
   ,@CREDITOS INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Asignatura
    (AREA_ID ,REGIMEN_ID ,NOMBRE ,HORASSEMANA ,HORASCUATRIMESTRE ,CREDITOS)
    VALUES
    (@AREA_ID ,@REGIMEN_ID ,@NOMBRE ,@HORASSEMANA ,@HORASCUATRIMESTRE ,@CREDITOS)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Asignatura
    @ID INT
   ,@AREA_ID INT
   ,@REGIMEN_ID INT
   ,@NOMBRE VARCHAR(256)
   ,@HORASSEMANA INT
   ,@HORASCUATRIMESTRE INT
   ,@CREDITOS INT
AS
BEGIN
  BEGIN TRY
    UPDATE Asignatura SET
    AREA_ID = ISNULL(@AREA_ID, AREA_ID)
   ,REGIMEN_ID = ISNULL(@REGIMEN_ID, REGIMEN_ID)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,HORASSEMANA = ISNULL(@HORASSEMANA, HORASSEMANA)
   ,HORASCUATRIMESTRE = ISNULL(@HORASCUATRIMESTRE, HORASCUATRIMESTRE)
   ,CREDITOS = ISNULL(@CREDITOS, CREDITOS)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Asignatura
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Asignatura WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_MateriasPlan
    @ID INT OUTPUT
   ,@PLAN_ID INT
   ,@ASIGNATURA_ID INT
   ,@NIVEL_ID INT
   ,@CUATRIMESTRE_ID INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO MateriasPlan
    (PLAN_ID ,ASIGNATURA_ID ,NIVEL_ID ,CUATRIMESTRE_ID)
    VALUES
    (@PLAN_ID ,@ASIGNATURA_ID ,@NIVEL_ID ,@CUATRIMESTRE_ID)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_MateriasPlan
    @ID INT
   ,@PLAN_ID INT
   ,@ASIGNATURA_ID INT
   ,@NIVEL_ID INT
   ,@CUATRIMESTRE_ID INT
AS
BEGIN
  BEGIN TRY
    UPDATE MateriasPlan SET
    PLAN_ID = ISNULL(@PLAN_ID, PLAN_ID)
   ,ASIGNATURA_ID = ISNULL(@ASIGNATURA_ID, ASIGNATURA_ID)
   ,NIVEL_ID = ISNULL(@NIVEL_ID, NIVEL_ID)
   ,CUATRIMESTRE_ID = ISNULL(@CUATRIMESTRE_ID, CUATRIMESTRE_ID)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_MateriasPlan
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM MateriasPlan WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Correlativas
    @ID INT OUTPUT
   ,@ASIGNATURA_ID INT
   ,@CORRELATIVA_ID INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Correlativas
    (ASIGNATURA_ID ,CORRELATIVA_ID)
    VALUES
    (@ASIGNATURA_ID ,@CORRELATIVA_ID)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Correlativas
    @ID INT
   ,@ASIGNATURA_ID INT
   ,@CORRELATIVA_ID INT
AS
BEGIN
  BEGIN TRY
    UPDATE Correlativas SET
    ASIGNATURA_ID = ISNULL(@ASIGNATURA_ID, ASIGNATURA_ID)
   ,CORRELATIVA_ID = ISNULL(@CORRELATIVA_ID, CORRELATIVA_ID)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Correlativas
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Correlativas WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Persona
    @ID INT OUTPUT
   ,@APELLIDO VARCHAR(64)
   ,@NOMBRE VARCHAR(64)
   ,@DNI INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Persona
    (APELLIDO ,NOMBRE ,DNI)
    VALUES
    (@APELLIDO ,@NOMBRE ,@DNI)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Persona
    @ID INT
   ,@APELLIDO VARCHAR(64)
   ,@NOMBRE VARCHAR(64)
   ,@DNI INT
AS
BEGIN
  BEGIN TRY
    UPDATE Persona SET
    APELLIDO = ISNULL(@APELLIDO, APELLIDO)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DNI = ISNULL(@DNI, DNI)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Persona
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Persona WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE I_Alumno
    @ID INT OUTPUT
   ,@PERSONA_ID INT
   ,@PLANESTUDIO_ID INT
   ,@LEGAJO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Alumno
    (PERSONA_ID ,PLANESTUDIO_ID ,LEGAJO)
    VALUES
    (@PERSONA_ID ,@PLANESTUDIO_ID ,@LEGAJO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
CREATE PROCEDURE U_Alumno
    @ID INT
   ,@PERSONA_ID INT
   ,@PLANESTUDIO_ID INT
   ,@LEGAJO INT
AS
BEGIN
  BEGIN TRY
    UPDATE Alumno SET
    PERSONA_ID = ISNULL(@PERSONA_ID, PERSONA_ID)
   ,PLANESTUDIO_ID = ISNULL(@PLANESTUDIO_ID, PLANESTUDIO_ID)
   ,LEGAJO = ISNULL(@LEGAJO, LEGAJO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
 
 
CREATE PROCEDURE D_Alumno
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Alumno WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;

